name: flutter_odoo_rpc
description: Odoo RPC Client library for Dart with session changes tracking via steam.
version: 0.6.0
homepage: https://github.com/chandrabezzo/odoo-rpc-dart
repository: https://github.com/chandrabezzo/odoo-rpc-dart

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  http: ^1.1.0
  crypto: ^3.0.0
  flutter_lints: ^2.0.0

dev_dependencies:
  test: ^1.16.5
